version: '3.9'
services:
  db:
    image: ${DB_IMAGE}
    container_name: mongodb
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345  
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo db:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3  
    restart: unless-stopped

  server:
    container_name: server_api
    image: api
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://localhost:4000/api/peliculas || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    links:
      - db
    depends_on:
      - db
 
